### ISSUE TITLE
Submission - To do Apps

### ISSUE THREAD

**Issue by RichardOwen2** [pmb-community/JS-Lanjutan#1]
Berikut adalah tugas akhir yang harus diselesaikan oleh peserta bootcamp. Berikut adalah deskripsi tugasnya dan skala penilaian yang diusulkan:

Deskripsi Tugas:
Buatlah halaman web To do apps dengan fungsionalitas :

```TS
Wajib :
1. Dapat menambahkan task baru (hal yang dilakukan dan tanggal) dan masuk ke daftar "Yang akan dilakukan"
2. Dapat menyelesaikan suatu task dan memindahkannya ke daftar "Yang sudah dilakukan"
3. Dapat mengembalikan task yang sudah selesai ke daftar "Yang akan dilakukan"
4. Data tersimpan meskipun direfresh atau web ditutup

Opsional :
1. Dapat menghapus task yang sudah selesai
2. Membuat fitur search
```

Contoh Tampilan Web :
![Screenshot 2023-06-21 103425](https://github.com/pmb-community/JS-Lanjutan/assets/104406943/ca8f0722-4c6f-4766-a16a-8a27ecc1f368)

Deadline :
Deadline tugas ini adalah 26 Juni 2023

Format Pengumpulan:
Pengumpulan dari tugas ini ada 2 link yaitu link repo proyek dan link website yang sudah di hosting menggunakan github pages. Untuk tutorial hosting proyek menggunakan github pages ada pada link ini https://youtu.be/rgDDWhQe-ow.

Skala Penilaian :
```TS
1. Fungsionalitas (90 Poin)
   - Semua Ketentuan Wajib terpenuhi tanpa BUG (70 Poin)
   - Semua Kententuan Opsional terpenuhi (20 Poin)

2. Tampilan (20 Poin)
   - Tampilan yang ramah dimata dapat poin plus
```

Hint :
1. Untuk Penggunaan Id gunakanlah tanggal
```TS
const id = +new Date();
```

2. Array Function
```TS
array.map(function(element) { task }) // untuk melakukan perluangan setiap element
array.push(item) // untuk menambahkan item pada array

array.filter(function(element) { task }) // untuk menghapus item tertentu jika kondisi terpenuhi
array.find(function(element) { task }) // untuk menemukan item tertentu jika kondisi terpenuhi
```

3. Web Storage
```TS
// Mengambil data dari cache storage
const data = JSON.Parse(localStorage.getItem(CACHE_KEY));

// Menyimpan data di cache storage
localStorage.setItem(CACHE_KEY, JSON.stringify(data));
```

Jika ada pertanyaan, tanya saja di grup 👍

**Comment by fzhnf** [comment]
Link repo: https://github.com/fzhnf/fzhnf.github.io/tree/main
Link Site: https://fzhnf.github.io/

**Comment by Dillaayh** [comment]
dilla ayu_11221031
link repo : https://github.com/Dillaayh/Dillaayh.github.io.git
link hipo : https://dillaayh.github.io/

**Comment by iqbalfhrzii** [comment]
Iqbal Fahrozi_11221034
link repo : https://github.com/iqbaalr/iqbaalr.github.io
link host : https://iqbaalr.github.io

**Comment by Dillaayh** [comment]
dilla ayu_11221031
link repo : https://github.com/Dillaayh/Dillaayh.github.io.git
link host : https://dillaayh.github.io/

**Comment by reno99986** [comment]
Reno Fahrezi Purnomo_11221051
repo: https://github.com/reno99986/tugasjs
host: https://reno99986.github.io/tugasjs/

**Comment by rapliultraman** [comment]
Rafli Pratama Y_11221090
link host: https://rapliultraman.github.io/Submission/
link repo: https://github.com/rapliultraman/Submission.git

**Comment by dionp3** [comment]
Dion Prayoga_11221058
Repo : https://github.com/dionp3/dionp3.github.io.git
Host : https://dionp3.github.io/

**Comment by SyifaMaulida18** [comment]
Syifa Maulida_11221007
Repo : https://github.com/SyifaMaulida18/SyifaMaulida18.github.io.git
Host : https://syifamaulida18.github.io/

**Comment by Wiraproject** [comment]
Wiranto_11221030
Repo : https://github.com/Wiraproject/Wiraproject.github.io
Host : https://wiraproject.github.io/

**Comment by zayfitri** [comment]
Isnaini_11221072
Repo: https://github.com/zayfitri/zayfitri.github.io.git
Host: https://zayfitri.github.io/

**Comment by Mocfigh** [comment]
Arifia_11221061
Repo : https://github.com/Mocfigh/Mocfigh.JS.github.io.git
Host : https://mocfigh.github.io/Mocfigh.JS.github.io/

**Comment by desssti06** [comment]
Desti - 11221033
repo : https://github.com/desssti06/to-do-list.git
host : https://desssti06.github.io/to-do-list/
